---
title: "385_project_Fall_2019"
author: "Dmitriy Borzhkovskiy, Giovanni Rodriguez, Duyen Ho, Jason Han"
date: "12/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
ccso = read.csv("CCSO Data.csv")
#released reasons for each race, take the percentage of each race in each major category
#election days,


View(ccso)
attach(ccso)
conversion = vars(Days.in.Jail,Hours,Minutes)
to_num = function(x) {
  as.numeric(as.character(x))
}

#total days spent in jail
ccso1 = ccso %>% 
  select(-c(BOOKING.NUMBER,JACKET.NUMBER,JACKET.TYPE,MILITARY,STATUTE.TYPE,CHARGE.STATUTE)) %>%
  mutate(total_days = to_num(Days.in.Jail) + to_num(Hours)/24 + to_num(Minutes)/1440) %>%
  group_by(RACE) %>%
  summarise(avg = mean(total_days,na.rm = T))
View(ccso1)
#this is for the same crime across race, View(ccso2) and use command f
ccso2 = ccso %>% 
        select(-c(BOOKING.NUMBER,JACKET.NUMBER,JACKET.TYPE,MILITARY,STATUTE.TYPE,CHARGE.STATUTE)) %>%
        subset(RACE != "" & RACE != "Unknown") %>%
        mutate(total_days = to_num(Days.in.Jail) + to_num(Hours)/24 + to_num(Minutes)/1440) %>%
        group_by(RACE,CRIME.CODE) %>%
        summarise(total = n(),avg = round(mean(total_days,na.rm = T),digits = 4)) # a min is .0007 days
ccso2 <- ccso2 %>% rename(Days = avg)
ccso3 = ccso %>% 
        select(-c(BOOKING.NUMBER,JACKET.NUMBER,JACKET.TYPE,MILITARY,STATUTE.TYPE,CHARGE.STATUTE)) %>%
        subset(RACE != "" & RACE != "Unknown") %>%
        mutate(total_days = to_num(Days.in.Jail) + to_num(Hours)/24 + to_num(Minutes)/1440) %>%
        group_by(RACE,EMPLOYMENT.STATUS) %>%
        summarise(total=n(), avg = round(mean(total_days,na.rm = T),digits = 4))
ccso3 = ccso3 %>% rename(Days = avg)
levels(RACE)
class(ccso2)
View(ccso2)
View(ccso1)
```





```{r, echo=FALSE}
library(shiny)
ui <- fluidPage(
  h1("Dmitriy, Giovanni, Duyen, Jason"),
  
  #tags$head(tags$style("Dmitriy, Giovanni, Duyen, Jason {color:red;}")),
  
  # App title ----
  titlePanel("Champaign County Jail (2011-2016)"),
  tabsetPanel(               
    tabPanel("Crime Code",sidebarLayout(
      sidebarPanel(
        selectInput("crime","Select a Crime code :",unique(ccso2$CRIME.CODE),selected = "AGGRAVATED ASSAULT")
        ),
      mainPanel(
        plotOutput("plot"),
        tableOutput("contents")
        )
    )
    ),
    tabPanel("Employment Status", sidebarLayout(
      sidebarPanel(
        selectInput("Employment","Select an Employment Status", unique(ccso3$EMPLOYMENT.STATUS),selected = "STUDENT")
      ),
      mainPanel(
        plotOutput("eplot"),
        tableOutput("emp")
      )
    ))
  )
)
      # tabPanel("Employment",
      #   sidebarLayout(
      #     sidebarPanel(selectInput("Employment", "Select Employment Status:",unique(ccso2$EMPLOYMENT.STATUS),selected = "STUDENT")
      #          ),
      #          mainPanel(
      #            plotOutput("plot"),
      #            tableOutput("contents")
      #          )
      #   )
      # )
    

# Define server logic to read selected file ----
server <- function(input, output) {
  crime = reactive(
    return(input$crime)
  )
  
  output$contents <- renderTable({
    
  c = crime()
  table_name = ccso2 %>% 
              filter(CRIME.CODE == c)
  table_name
    
  })
  emp = reactive(
    return(input$Employment)
  )
  output$emp <- renderTable({
    e = emp()
    table_emp = ccso3 %>% filter(EMPLOYMENT.STATUS == e)
  })
  output$eplot = renderPlot({
    e = emp()
    table_emp = ccso3 %>% filter(EMPLOYMENT.STATUS == e)
    ggplot(table_emp, aes(x=RACE,y=Days)) + geom_bar(stat = "identity")
  })
  
  output$plot = renderPlot({
  c = crime()
  table_name = ccso2 %>% 
              filter(CRIME.CODE == c)
    ggplot(table_name, aes(x=RACE, y=Days)) +
      geom_bar(stat="identity")
  })
}
# Run the app ----
shinyApp(ui, server)
```

